// Generated by https://quicktype.io

export interface PokemonResponse {
  count: number;
  next: string;
  previous: null;
  results: Result[];
}

export interface Result {
  name: string;
  url: string;
}
export interface SimplePokemon {
  pokemonId: string;
  name: string;
  pokemonPicture: string;
  color?: string;
}
